POST http://localhost:4000/chit
content-type: application/json

{
    "user":
    {
        "firstname": "John",
        "lastname": "Doe",
        "username": "realjohndoe"
    },
    "content": "My name is John and this is my first Chit. I am excited to be here.",
    "time": "2021-07-01T12:00:00Z"
      
}

###

POST http://localhost:4000/chit
content-type: application/json

{
    "user":
    {
        "firstname": "Will",
        "lastname": "Cooper",
        "username": "will"
    },
    "content": "I have created Chitter. I am basically Tesla.",
    "time": "2021-06-01T12:00:00Z"
      
}